feat: criação da home e ajuste de imagens para a pasta assets , adica…
Charlie-Pencal/CRLinePage pull request #7
Opened 2023-10-22 14:40 UTC by aleodoro93

…o de props referente a fonte ao componente botao.

atentar se a pasta assets: todas imagens foram migradas para assets ao invés de public pois estava dando conflito de importação.
sendo assim tendo q mudar a importacao.

2023-10-22 18:18 UTC, julianebueno requested changes
Foi comitado o arquivo Rotas.jsx junto, ele já está configurado na branch main e não pode/precisa ser alterado

2023-10-22 19:14 UTC, aleodoro93 commented
feito a remoção

2023-10-22 22:37 UTC, julianebueno approved these changes

2023-10-23 14:10 UTC, Charlie-Pencal approved these changes

2023-10-23 14:11 UTC, merged